

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/ 
train: train/images
val: valid/images  
# test: test-dev2017.txt  

# Classes
names:
  0: qua_trung